//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.21 at 07:15:05 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://manikala.com/shop/ws/greeting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.manikala.shop.ws.greeting;
