spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: 2000
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true
